### ISSUE TITLE
No default logger is defined

### ISSUE THREAD

**Issue by castodius** [enfogroup/enfo-logger#1]
Steps to recreate:
1. Install logger and winston
2. Import default logger using `const logger = require('@enfo/enfo-logger).logger`
3. Log using logger.info('Hello world!');

Expected result:
Hello world gets logged

Actual result:
NodeJS informs you that logger is not defined.

I think we forgot to export it.

**Comment by kabo** [comment]
```js
import logger from '@enfo/enfo-logger'
```
is not
```js
const logger = require('@enfo/enfo-logger).logger
```
but rather
```js
const logger = require('@enfo/enfo-logger)
```
