### ISSUE TITLE
Feature request - pretty printing

### ISSUE THREAD

**Issue by castodius** [enfogroup/enfo-logger#2]
When using the default schema for logging the logs turn out real dense. No spaces at all. An option should be added for pretty printing. I think an environment variable makes sense.
`PRETTY_PRINT`

This would enable us to make our logs more readable when used locally.

**Comment by kabo** [comment]
Compact logs make for cheaper logs in CloudWatch :)

I'm no fan of the environment variable idea. The formatter in the schema gets set on import, so you'd have to set that environment variable before importing enfo-logger.

doing something like 
```js
process.env.PRETTY_PRINT = 'yes'
logger.info('some pretty printing here')
process.env.PRETTY_PRINT = 'no'
```
wouldn't work as expected.

We could easily create another schema that pretty prints the json though. Then you can choose which schema you want in your code based on whatever you want. You can even create 2 loggers and switch between them as you please.
